version: '2'
volumes:
  data-mysql:
    external:
      name: cake-data-mysql

services:
  cake-manager:
    image: dididu/cake-manager
    container_name: cake-manager
    ports:
     - "8282:8080"
    links:
     - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=p4SSW0rd
      - MYSQL_DATABASE=cake
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=dbp4ss

    volumes:
      - data-mysql:/data/db
