version: '2'
volumes:
  data-mysql:
    external:
      name: cake-data-mysql

services:
  cake-manager:
    image: dididu/cake-manager
    container_name: cake-manager
    restart: always
    env_file:
     - cake.env
    ports:
     - "8282:8080"
    links:
     - mysql:cakedb

  mysql:
    image: mysql:latest
    container_name: mysql
    restart: always
    env_file:
     - cake.env

    ports:
      - "3306:3306"

    volumes:
      - data-mysql:/data/db