spring:
  profiles: default
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:sampletest;MODE=MySQL
---
spring:
  profiles: container
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: mysql
    database: cake
    username: ${MYSQL_ENV_MYSQL_USER}
    password: ${MYSQL_ENV_MYSQL_PASSWORD}
    initialize: true