spring:
  profiles: default
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:sampletest;MODE=MySQL
server:
  port: 8282
---
spring:
  profiles: container
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://cakedb/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    initialize: true

  jpa:
    hibernate:
      ddl-auto: update
